const {JSDOM, VirtualConsole} = require('jsdom');
const fs = require('fs');
const path = require('path');
const target=process.argv[2] || path.join(__dirname,'../Saida/qualidade-0.11.1/Relatorio/relatorio.html');
const errors=[];
const vc=new VirtualConsole();
vc.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(fs.readFileSync(target,'utf8'),{runScripts:'dangerously',virtualConsole:vc});
const d=dom.window.document;
function check(value,message){if(!value)throw Error(message)}
const memory=d.getElementById('memory').textContent;
check(memory.includes('Habilidade: fogo') && memory.includes('exclusivo'),'Habilidade exclusiva de fogo');
check(memory.includes('Habilidade demonstrada: gelo'),'Gelo demonstrado');
check(memory.includes('Posse: chave'),'Nome do item em vez de ID');
check(memory.includes('Localização: torre'),'Nome do local em vez de ID');
check(!/obj_[0-9a-f]|loc_[0-9a-f]/.test(memory),'IDs internos não apresentados como valores');
check(memory.includes('dispositivo de Íris') && memory.includes('dispositivo de Tomás'),'Identidades distintas visíveis');
check(d.querySelectorAll('#memory blockquote').length===7,'Evidência dos sete fatos');
const moduleSelect=d.getElementById('module');
moduleSelect.value='global_coherence';moduleSelect.dispatchEvent(new dom.window.Event('input'));
check(d.querySelectorAll('.card').length===1,'Somente conflito fogo/gelo');
check(errors.length===0,errors.join('\n'));
console.log('DOM v0.11.1 aprovado: fatos, identidades, valores legíveis, evidências e filtro global.');
